#!/usr/bin/env ruby

require_relative '../lib/ragent'

workdir=Dir.pwd

ragent=Ragent.setup(
  log_level: ENV['RAGENT_LOG_LEVEL'] || 'info',
  workdir: workdir
)

eval File.read(ragent.workdir.join("config.ragent"))
